Repository wildcodeschool-2025-03/js-p3-idealy, pull requests merged in 2025-07, with the labels that each got.

#70 server router fix error new user
  server/src/router.ts
Labels: fix

#72 feat(auth): auto-logout on token removal or expiration with alert dis…
  client/src/context/AuthContext.tsx
  client/src/utils/isTokenExpired.ts
Labels: enhancement

#74 feat: améliore UX - text editor + confirmation avant envoi sans perte…
  client/src/components/TextEditor.tsx
  client/src/components/ui/SoumissionFeedback.tsx
  client/src/pages/Soumettre.tsx
Labels: fix

#77 add fix bug
  client/src/context/AuthContext.tsx
Labels: fix

#78 S6 soumettre file validation
  client/src/components/ui/PieceJointeButton.tsx
  client/src/components/ui/SoumissionFeedback.tsx
  client/src/pages/Soumettre.tsx
  client/src/utils/validateFiles.ts
Labels: enhancement, fix

#82 Feat: middleware validation idées avec tests et corrections types TS …
  server/package.json
  server/src/modules/idea/validateIdeaSchema.ts
  server/src/modules/item/itemActions.ts
  server/src/modules/item/itemRepository.ts
  server/src/router.ts
  server/tests/fixtures/test.pdf
  server/tests/idea/validateIdeaSchema.int.spec.ts
  server/tests/idea/validateIdeaSchema.spec.ts
  server/tests/install.test.ts
  server/tests/item/routes.spec.ts
  server/tests/statistics/routes.spec.ts
Labels: enhancement, fix

#87 US_72_109 - See file in detail + votes in detail + fix name when comment
  client/src/components/MediaModal.tsx
  client/src/pages/Detail.tsx
  server/src/modules/idea/ideaActions.ts
  server/src/modules/idea/ideaRepository.ts
  server/src/modules/idea/validateIdeaSchema.ts
  server/src/router.ts
Labels: enhancement, fix

#88 S7 fix bug UI ux
  client/src/components/AuthGuard.tsx
  client/src/components/IdeaCard.tsx
  client/src/components/Statistiques.tsx
  client/src/components/TextEditor.tsx
  client/src/components/ui/DeadlineModal.tsx
  client/src/components/ui/SoumissionFeedback.tsx
  client/src/pages/Information.tsx
  client/src/pages/Soumettre.tsx
  server/src/modules/statistics/statisticsRepository.ts
Labels: fix

#95 S7 fix texteditor rendering
  client/src/App.css
  client/src/components/IdeaCard.tsx
  client/src/utils/sanitizeAndTruncate.ts
  server/src/modules/idea/validateIdeaSchema.ts
Labels: fix

#97 Fix - Account/Password fix
  client/src/components/EditProfilModal.tsx
  client/src/pages/Compte.tsx
Labels: fix

#104 fix + css
  client/src/pages/Admin.tsx
  client/src/pages/Contact.tsx
  server/database/schema.sql
Labels: fix

#105 css carousel
  client/src/components/Carousel.tsx
Labels: enhancement

#108 Bcrypt hash ok
  package-lock.json
  server/database/schema.sql
  server/package.json
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
Labels: enhancement
