Repository wildcodeschool-2025-03/js-p3-idealy, pull requests merged in 2025-06, with the labels that each got.

#14 add footer
  client/public/Facebook.svg
  client/public/Instagram.svg
  client/public/Linkedin.svg
  client/src/components/Footer.tsx
Labels: enhancement

#16 US_08_Header - Responsive mobile - desktop
  client/package.json
  client/src/App.css
  client/src/components/Header.tsx
  client/src/main.tsx
  package-lock.json
Labels: enhancement

#18 add carousel component
  client/src/components/Carousel.tsx
Labels: enhancement

#19 Us 38 40 about
  client/src/assets/images/David.png
  client/src/assets/images/Guillaume.png
  client/src/assets/images/Maxime.png
  client/src/assets/images/Messica.png
  client/src/components/Header.tsx
  client/src/pages/Apropos.tsx
  package-lock.json
Labels: enhancement

#30 S4 us32 fix idea action
  server/src/modules/idea/ideaActions.ts
Labels: fix

#34 S4 us 110 information css + US_69
  client/src/components/IdeaCard.tsx
  client/src/pages/Information.tsx
  client/src/pages/NotFound.tsx
Labels: enhancement, fix

#36 page principale : see recent ideas + idea's user + validated ideas + carousel for mobile (readAll + filtre)
  client/src/components/Carousel.tsx
  client/src/pages/Principal.tsx
  server/src/modules/idea/ideaActions.ts
  server/src/modules/idea/ideaRepository.ts
Labels: enhancement, fix

#48 admin page with test + delete and put idea (accept or refuse)
  client/src/main.tsx
  client/src/pages/Admin.tsx
  client/src/pages/Detail.tsx
  server/database/schema.sql
  server/src/modules/idea/ideaActions.ts
  server/src/modules/idea/ideaRepository.ts
  server/src/router.ts
Labels: enhancement

#50 add .envsample with comment with step and add statut error if emailjs…
  client/.env.sample
  client/src/pages/Contact.tsx
Labels: bug, fix

#52 uselogin dans la page principale
  client/src/pages/Principal.tsx
Labels: enhancement

#53 Page admin button confirmation avant de supprimer valider refuser
  client/src/pages/Admin.tsx
  server/src/modules/idea/ideaActions.ts
Labels: enhancement

#54 US_57_COMPTE - Connexion / Deconnexion = OK
  client/src/components/Deco_Del_Button.tsx
  client/src/components/EditProfilModal.tsx
  client/src/components/IdeaCard.tsx
  client/src/components/PersonalInfo.tsx
  client/src/context/AuthContext.tsx
  client/src/pages/Compte.tsx
  server/public/uploads/a2js369po2c9jwln6ryfdkq20.webp
  server/public/uploads/kp573i1ra9yd817lcjwwe7idt.jpeg
  server/public/uploads/w6da9vch3txxptbqdlg23iuj2.jpeg
  server/src/modules/user/userActions.ts
Labels: enhancement

#55 add text editor
  client/package.json
  client/src/App.css
  client/src/components/IdeaCard.tsx
  client/src/components/TextEditor.tsx
  client/src/pages/Soumettre.tsx
  client/src/utils/sanitizeAndTruncate.ts
Labels: enhancement

#57 Fixes various bugs
  client/src/pages/Apropos.tsx
  client/src/pages/Contact.tsx
  client/src/pages/Principal.tsx
  package-lock.json
Labels: bug

#60 add history of ideas and possibility to delete an user in admin page
  client/src/pages/Admin.tsx
  server/database/schema.sql
  server/src/modules/idea/ideaActions.ts
  server/src/modules/idea/ideaRepository.ts
  server/src/router.ts
Labels: enhancement

#63 US_58_COMPTE - Delete button + CSS Desktop
  client/src/components/Deco_Del_Button.tsx
  client/src/components/EditProfilModal.tsx
  client/src/components/PersonalInfo.tsx
  client/src/context/AuthContext.tsx
  client/src/pages/Contact.tsx
Labels: enhancement, fix
